sudo: false
language: ruby
rvm:
  - 2.5.1
before_install: gem install bundler -v 1.16.2
deploy:
  provider: rubygems
  gem: monban-repository
  on:
    tags: true
  api_key:
    secure: "F4xwXKdn2jwnfomfXfUkj4eQ0vdztXhGr63mQRoB5DfHRxv63iqG5mRxYqOzge77JLhJHOIiWp1OO2tweeRXssbNqOtdOUXsEnmzSe+PVJu6X+jD0/8WIMRkINSYQAH1fgVYAVlFvf2Z5S3c8iSP3KgacmpV+NEehPumsw4QIfE/y8AlH+tUjd2QKTTzIuJM/JSen4kxFtziUIoc1ejbB/tZW3+HU3Cv2BfOb0UXm/ZzCylYrYKUJM836vo0529EP2LBg3/V2wLzh+jJEQdU2+VJoAY5tVj3rS1ciEgZuMVgIPVMAYO45GAVXEDHJkm+YzC5VVTKAv6L+BZ4pWY1xFLjYc80nWM/syDJ/RDFhfGueDD90aIq3h4uB91+A4/LCsK7ZxONakn/wNvBE5vo67uyWKp7ADKzAZON3STuhb9yBN6uHIad5wdup8NbRpUy7aTlrEABMwq6MfSgFiM9/mB7e81DE672274qr2bO4iRlydyp33wciiroyBvUwIckMtel9N8xQ9q/j3kiBvXKqSswY8lh8AN5py26wr13F/yt6yJ5OI0vt0jdKZ+f5K4XLVNv/9VGTOkjM/4H9EF5YHKrofg6GH2cGObXfccx6PNoGVnnMaRcReRXaguv6ausbZEEQu+Z1kjQQcyqJM0E02ACg4yERo3LONYG12i7g5o="
